version: "3.3"
services:
  besu-node1:
    build:
      context: .
      dockerfile: ./bootnode/Dockerfile
      args:
        - BESU_VERSION
    environment:
      - NODE_INDEX=1
      - RPC_PORT=8545
      - RPC_WS_PORT=8546
      - P2P_PORT=30303
    ports:
      - 8545:8545
      - 8546:8546
      - 30303:30303
    healthcheck:
      test: ["CMD", "curl", "-X", "POST", "--data", '{"jsonrpc":"2.0","method":"net_listening","params":[],"id":0}', "http://127.0.0.1:8545"]
      interval: "30s"
      timeout: "30s"
      retries: 3
  besu-node2:
    build:
      context: .
      dockerfile: ./node/Dockerfile
      args:
        - BESU_VERSION
    environment:
      - NODE_INDEX=2
      - BOOTNODE_INDEX=1
      - BOOTNODE_SERVICE=besu-node1
      - BOOTNODE_PORT=30303
      - RPC_PORT=8547
      - RPC_WS_PORT=5468
      - P2P_PORT=30304
    ports:
      - 8547:8547
      - 8548:8548
      - 30304:30304
    healthcheck:
      test: [ "CMD", "curl", "-X", "POST", "--data", '{"jsonrpc":"2.0","method":"net_listening","params":[],"id":0}', "http://127.0.0.1:8547" ]
      interval: "30s"
      timeout: "30s"
      retries: 3
    depends_on:
      besu-node1:
        condition: service_healthy
  besu-node3:
    build:
      context: .
      dockerfile: ./node/Dockerfile
      args:
        - BESU_VERSION
    environment:
      - NODE_INDEX=3
      - BOOTNODE_INDEX=1
      - BOOTNODE_SERVICE=besu-node1
      - BOOTNODE_PORT=30303
      - RPC_PORT=8549
      - RPC_WS_PORT=8550
      - P2P_PORT=30305
    ports:
      - 8549:8549
      - 8550:8550
      - 30305:30305
    healthcheck:
      test: [ "CMD", "curl", "-X", "POST", "--data", '{"jsonrpc":"2.0","method":"net_listening","params":[],"id":0}', "http://127.0.0.1:8549" ]
      interval: "30s"
      timeout: "30s"
      retries: 3
    depends_on:
      besu-node1:
        condition: service_healthy
  besu-node4:
    build:
      context: .
      dockerfile: ./node/Dockerfile
      args:
        - BESU_VERSION
    environment:
      - NODE_INDEX=4
      - BOOTNODE_INDEX=1
      - BOOTNODE_SERVICE=besu-node1
      - BOOTNODE_PORT=30303
      - RPC_PORT=8551
      - RPC_WS_PORT=8552
      - P2P_PORT=30306
    ports:
      - 8551:8551
      - 8552:8552
      - 30306:30306
    healthcheck:
      test: [ "CMD", "curl", "-X", "POST", "--data", '{"jsonrpc":"2.0","method":"net_listening","params":[],"id":0}', "http://127.0.0.1:8551" ]
      interval: "30s"
      timeout: "30s"
      retries: 3
    depends_on:
      besu-node1:
        condition: service_healthy
